# Generated by Django 4.2.2 on 2023-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
