# Generated by Django 4.2.2 on 2023-08-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_compraproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(default=2, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='url_avatar',
            field=models.CharField(default='https://static.thenounproject.com/png/5034901-200.png'),
        ),
    ]
